### ISSUE TITLE
Error when restarting or shutting down the PC

### ISSUE THREAD

**Issue by vitalii0133** [ShadowMonster99/millennium-steam-patcher#14]
After installing millenium patcher, I get this error when restarting or shutting down the PC:

Steam.exe - Application error. 
The instruction at 0x00000000610B68D0 referenced memory at 0x0000000000000000. The memory could not be read.

The error disappears as soon as I delete millennium patcher.

**Comment by ShadowMonster99** [comment]
- Does this happen every single time your pc is shut down?
- Are you running steam with developer mode or anything other than native?
- Does it occur when you don't have a skin selected, or maybe different skins then the one you're using?

It's most likely becuase you're computers shutting down and steam does something that millennium isn't prepared to handle. Its very difficult for me to simply just debug something like this but I can assure you it isn't anything to worry about and wont cause any damage to steam or millennium.

**Comment by vitalii0133** [comment]
@ShadowMonster99

* Yes
* No
* With any skin, including the standard one

I noticed one feature, this error occurs only if the file explorer or any folder is open along with steam when the pc is turned off.

**Comment by ShadowMonster99** [comment]
Interesting. I'll have a look into it. Thanks for bringing it to my attention. You can remain using millennium though for the time being as nothing is being damaged.
