### ISSUE TITLE
completely broken in the steam beta client

### ISSUE THREAD

**Issue by Morphof** [ShadowMonster99/millennium-steam-patcher#19]
UI does not show at all, sometimes when starting steam, it shows an error message involving millennium and closes. When rolling back, millennium works fine. 
![Screenshot 2024-03-10 190753](https://github.com/ShadowMonster99/millennium-steam-patcher/assets/161979136/817a348c-ec96-4a28-a14d-80baf78b0340)

**Comment by Morphof** [comment]
also this error shows for any skin

**Comment by Morphof** [comment]
Reinstalled steam, was an issue with my steam client

**Comment by ShadowMonster99** [comment]
it was a problem with a theme you have installed. it will be fixed as soon as possible
