### ISSUE TITLE
latest Millennium.Installer v1.0.8 Update Needs Fixed

### ISSUE THREAD

**Issue by MarshMeadow** [ShadowMonster99/millennium-steam-patcher#20]
![image](https://github.com/ShadowMonster99/millennium-steam-patcher/assets/88599122/1ae29ff3-f651-4855-b4ab-0f052374ad2d)

https://discord.com/invite/MXMWEQKgJF

![image](https://github.com/ShadowMonster99/millennium-steam-patcher/assets/88599122/d542bd39-81d7-47a7-b30b-6304c36d60da)

**Comment by ShadowMonster99** [comment]
will be fixed in the new update, thanks for reminding me. for now use:
- https://millennium.web.app/discord
