### ISSUE TITLE
What the fuck is this bullshit popup that forcefully opens the repo

### ISSUE THREAD

**Issue by Shywizz** [ShadowMonster99/millennium-steam-patcher#7]
please fix this.

**Comment by ShadowMonster99** [comment]
There isn't one. this is a personal project not made by an organization or anyone who cares what you think. refrain from using hostile language considering I don't _have_ to do anything for you so don't come on here like that.

The only 'popup' is one that prompts you to install a new update.

**Comment by TheBearodactyl** [comment]
> please fix this.

ik i'm late but don't be rude bro

https://github.com/user-attachments/assets/6fdfac21-6224-457e-91b0-0ca996ada48f
